language: ruby
cache: bundler
gemfile: docs/Gemfile
before_install:
  - gem update --system
script:
  - bundle exec jekyll algolia --source docs --destination docs/_site --config docs/_config.yml
branches:
  only:
    - master
rvm:
 - 2.4
